# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48d429eba19d4d5662abec77941b2d64e46573f6cdbdd9dc7da396ae2da042092d2b02e5f802253b906de1495bd2413097a527e15cd8b7ad32e32dfeda1b679b

test:
  secret_key_base: a8d884891218a8300cb0bf1cb6228bf06d085f6ddbecafd013282d39737ff88e5800b4aa4717c2da3bcd36fe1430242dc68e26bb967198f201182ec57d92790a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
